title: CraftChronicles
author: Dr. Anthony Onoja
description: Faith, Politics, and African Consciousness.
theme: jekyll-theme-midnight
show_downloads: false

# Crucial for your subfolder setup
baseurl: "/CraftChronicles"
url: "https://donmaston09.github.io"

# This looks for the image inside your assets folder
logo: /assets/banner.png

header_pages:
  - index.md
