title: CraftChronicles
author: Dr. Anthony Onoja
description: Faith, Politics, and African Consciousness.
theme: jekyll-theme-midnight # Or 'jekyll-theme-hacker' for a more 'Intelligence Report' feel
google_analytics: # You can add a tracking ID later
show_downloads: false # This removes the 'Download on GitHub' buttons which look unprofessional for a blog
header_pages:
  - index.md
# Add this line below to point to your image
logo: /assets/banner.png
